apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trigger-v4.fullname" . }}-secrets
  labels:
    {{- include "trigger-v4.labels" . | nindent 4 }}
type: Opaque
data:
  session-secret: {{ .Values.secrets.sessionSecret | b64enc | quote }}
  magic-link-secret: {{ .Values.secrets.magicLinkSecret | b64enc | quote }}
  encryption-key: {{ .Values.secrets.encryptionKey | b64enc | quote }}
  managed-worker-secret: {{ .Values.secrets.managedWorkerSecret | b64enc | quote }}
  object-store-access-key-id: {{ .Values.secrets.objectStore.accessKeyId | b64enc | quote }}
  object-store-secret-access-key: {{ .Values.secrets.objectStore.secretAccessKey | b64enc | quote }}
---
{{- if and .Values.registry.enabled .Values.registry.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trigger-v4.fullname" . }}-registry-auth
  labels:
    {{- include "trigger-v4.labels" . | nindent 4 }}
type: Opaque
data:
  htpasswd: {{ htpasswd .Values.registry.auth.username .Values.registry.auth.password | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trigger-v4.fullname" . }}-registry-secret
  labels:
    {{- include "trigger-v4.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "trigger-v4.imagePullSecret" . | b64enc }}
{{- else if and .Values.registry.external .Values.registry.externalConnection.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trigger-v4.fullname" . }}-registry-secret
  labels:
    {{- include "trigger-v4.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "trigger-v4.imagePullSecret" . | b64enc }}
{{- end }}